apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: loki-stack
      version: "2.11.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    grafana:
      enabled: false
    promtail:
      enabled: false

