apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: promtail
      version: "6.13.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
    serviceAccount:
      create: true
    extraScrapeConfigs: |
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - action: replace
          source_labels: [__meta_kubernetes_pod_label_app]
          target_label: app

