apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-repo
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/infrastructure/ingress-nginx/helmrepository
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

