apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: wordpress
      version: 15.2.23
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    wordpressUsername: admin
    wordpressPassword: changeme
    externalDatabase:
      host: mysql.default.svc.cluster.local
      user: wordpress
      password: wordpress
      database: wordpress
    ingress:
      enabled: true
      hostname: app.local
      ingressClassName: nginx

