apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-release
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/infrastructure/ingress-nginx/helmrelease
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ingress-nginx-repo

